### ISSUE TITLE
Outdated FAP

### ISSUE THREAD

**Issue by casper89d** [0xchocolate/flipperzero-wifi-marauder#3] opened 2022-10-14 07:04 UTC
### Describe the bug.

FAP is outdated after compared to recent Flipper Marauder update. There are missing options and controls, to include items such incorrect file timestamps and multiple flipper device crashes.

### Reproduction

1. update flipper esp32-devboard with latest Flipper Marauder release.
2. Reboot Flipper
3. Navigate to [ESP32] WiFi Marauder.
4. 50/50 chance of Flipper crashing with message "NULL pointer dereference". If not, then observe missing new features/capabilities options on-screen.

**Comment by 0xchocolate** [comment] 2022-10-30 17:12
Closing as duplicate of https://github.com/0xchocolate/flipperzero-firmware-with-wifi-marauder-companion/issues/2 and https://github.com/0xchocolate/flipperzero-firmware-with-wifi-marauder-companion/issues/4

**Closed as not planned by 0xchocolate** 2022-10-30 17:12 UTC
Labels: bug
